### PR TITLE
GSoC ideas list clean up, add mentor names to the projects

### PR DESCRIPTION
**Pull request by shashi**
The GSoC administrators have requested us to make the format of our Idea items consistent, and to make sure each one has a list of recommended skills and potential mentors.

This is quite urgent, because in the event that we are accepted for GSoC students will start visiting the ideas page immediately.

Any new idea contributions are also welcome. While this PR is open I'll even copy-paste them from comments here :)

### CODE REVIEW

**Comment by shashi** [comment]
@ChrisRackauckas @MikeInnes help?

**Comment by tbreloff** [comment]
@shashi I don't think I'll be able to mentor anyone this year, but hopefully someone that's involved with JuliaPlots and JuliaML can step up for those projects.

**Comment by MikeInnes** [comment]
@tbreloff thanks for letting us know. Any chance you can reach out to those groups and find someone who can volunteer? We can't have the projects without a potential mentor (though it's also not binding if things change).

**Comment by ChrisRackauckas** [comment]
I'll do a separate PR for recommended skills for diffeq and numerics to make them a bit more exact. Some of these require in depth knowledge, some of these don't.

**Comment by ChrisRackauckas** [comment]
Maybe @pkofod or @SimonDanisch would be interested in helping on the Plots side of things? @pkofod for ML too. There has been a lot of interest in ML projects so we really should find someone.

**Comment by ChrisRackauckas** [comment]
We should standardize how we  do the mentors. Always include link to Github profile?

**Comment by MikeInnes** [comment]
Yup, linking to github or some other profile page / contact point is good.

**Comment by ChrisRackauckas** [comment]
@sbromberger will you be able to mentor the LightGraphs project?

**Comment by MikeInnes** [comment]
I'll merge this for now. @sbromberger mentioned that he could mentor; @shashi is going to update the numerics page when he has a moment.

**Comment by ChrisRackauckas** [comment]
@musm would you be willing to mentor Libm-based projects?

**Comment by ChrisRackauckas** [comment]
Alright. I was going to add some recommended knowledge for the numerics page, but I'll wait to see what you have.

**Comment by MikeInnes** [comment]
Actually, if you can take on the numerics do-over that'd be great – I'm pretty sure Shashi is sleeping right now anyway.

**Comment by ChrisRackauckas** [comment]
But still, have we found no one for ML? There have been quite a few requests for ML-related projects. We should find somebody and get a project list for that.

**Comment by pkofod** [comment]
You mean student or mentor?

**Comment by ChrisRackauckas** [comment]
Mentor

**Comment by sbromberger** [comment]
Either I or a combination of LG regulars should be able to mentor.

**Comment by shashi** [comment]
ping @vtjnash @yuyichao @StefanKarpinski @stevengj @barche @timholy @Keno who are mentioned here.

This PR got merged before I could ping you all, sorry about that! Please let me know if you want your name removed from any of projects, or added your name/suggest someone else for any project as well.

**Comment by vtjnash** [comment]
Thanks for dong this. I already edited some of mine - this prompted me to notice some of them were no longer quite as relevant / already completed.

I'll also just throw out there, that if I get contacted for a project that I don't feel is the right match, I'll still reply and try to match them up with someone who I think might be better able to mentor their project proposal.

**Pull request merged**
