### PR TITLE
adding license

### PR DESCRIPTION
**Pull request by hunterowens**
This might create issues, but this will open source the contents of the website. 

Discuss below.

### CODE REVIEW

**Comment by jiahao** [comment]
For the record, I agree to relicense all the content I have contributed to this repository under the new open source license which will be decided by this thread.

**Comment by hunterowens** [comment]
For the record, I agree to relicense all the content I have contributed to this repository under the new open source license which will be decided by this thread.

:+1:

**Comment by nalimilan** [comment]
For the record, I agree to relicense all the content I have contributed to this repository under the new open source license which will be decided by this thread.

(Given the ridiculous size of the changes I did, it would be quite funny to be the one blocking the process...)

**Comment by simonbyrne** [comment]
I didn't even know I modified anything, but...

For the record, I agree to relicense all the content I have contributed to this repository under the new open source license which will be decided by this thread.

**Comment by ViralBShah** [comment]
For the record, I agree to relicense my contributions I have contributed to this repository under the new open source license which will be decided by this thread.

**Comment by Carreau** [comment]
For the record, I agree to relicense all the content I have contributed to this repository under the new open source license which will be decided by this thread.

And I now understand why the first thing you should do in a repository is to put a LICENSE file. 
BTW should the LICENSE precise that the julia logo and trademark are copyrighted ? and/or can reference material that could be copyrighted ? Like link to GitHub, or even the term "GitHub". 

It's a real question, not a rhetorical one.

**Comment by jhasse** [comment]
For the record, I agree to relicense all the content I have contributed to this repository under the new open source license which will be decided by this thread.

I would favor the zlib license instead of MIT. But I just contributed a few parts, so I'm okay with anything. (Just wanted to promote the zlib license! Woohoo! zlib 4tw!)

**Comment by StefanKarpinski** [comment]
Why is the zlib license good?

**Comment by jhasse** [comment]
I find the [zlib license](http://en.wikipedia.org/wiki/Zlib_License) text easy to read and understand as a non native English speaker. I needed to read the MIT license multiple times to understand what is meant by "the Software". Btw: what does substantial mean?

Also the [MIT license](http://en.wikipedia.org/wiki/MIT_License) has multible versions (the FSF considers "MIT License" ambiguous), MIT YELLS AT ME USING CAPS and it's named after the MIT which I don't have anything to do with. And the important one: If I understand it correctly the MIT license forces me to include a license copy in *binary* distributions. Guess this doesn't apply for a website though ;)

**Comment by ViralBShah** [comment]
I say we as a community have attached ourselves to the MIT license, and the downsides are minor - but everyone is familiar with the MIT license and comfortable. I do like the zlib license, but I'd say let's just stick with MIT for now.

**Comment by staticfloat** [comment]
For the record, I agree to relicense all the content I have contributed to this repository under the new open source license which will be decided by this thread.

I love that we can all post the same thing here, and yet it's still useful for the discussion.  I agree we should stick to the MIT license for simplicity's sake; especially since it seems to provide the functionality we agree on.

**Comment by i2000s** [comment]
For the record, I agree to relicense all the content I have contributed to this repository under the new open source license which will be decided by this thread.

You guys are wonderful! I think MIT license will work well in our case. 
BTW, I saw many organizations and companies also have separated sets of [Contributor License Agreements](http://en.wikipedia.org/wiki/Contributor_License_Agreement) for contributors. For example, [this one for W3C](http://www.w3.org/community/about/agreements/cla/) and [this one for Ubuntu](http://assets.ubuntu.com/sites/ubuntu/1283/u/files/section/legal/Canonical-HA-CLA-ANY-I_v1.2.pdf). I didn't look into them too much. But seems CLA could help ease trademarks, patents or some other copyright disputes for organizations.

**Comment by Carreau** [comment]
> For the record, I agree to relicense all the content I have contributed to this repository under the new open source license which will be decided by this thread.
> 
> You guys are wonderful! I think MIT license will work well in our case. 
> BTW, I saw many organizations and companies also have separated sets of Contributor License Agreements for contributors. For example, this one for W3C and this one for Ubuntu. I didn't look into them too much. But seems CLA could help ease trademarks, patents or some other copyright disputes for organizations.

As far as I read [clahub](https://www.clahub.com/) and alike are a pain because you have to ask almost all new contributors to click the CLA, often integrated with Travis so when test fail you don't know if it's just about CLA, or real code issues.

A simple things would be to add a note in the "Contributing" that people canot say they were not warn to read when submitting PRs.

**Comment by shashi** [comment]
For the record, I agree to relicense all the content I have contributed to this repository under the new open source license which will be decided by this thread.

:v:

**Comment by jayschwa** [comment]
For the record, I agree to relicense all the content I have contributed to this repository under the new open source license which will be decided by this thread.

**Comment by StefanKarpinski** [comment]
CLAs make it possible for the party controlling the CLA to unilaterally relicense something. Without a CLA, you basically can't relicense a large project with many contributors – we're seeing why right here. That's a double edged sword: sometimes relicensing can be beneficial and helpful while other times it can be dangerous. If we had a CLA and some institution decided that they owned it they could then insist on changing the license of Julia to something more restrictive like the GPL, and require commercial users to purchase non-GPL licenses (this is how FFTW works). Without a CLA, such a scenario is basically impossible, so Julia is stuck, for better or worse, with the MIT license.

**Comment by pao** [comment]
For the record, I agree to relicense all the content I have contributed to this repository under the new open source license which will be decided by this thread.

**Comment by vtjnash** [comment]
For the record, I agree to relicense all the content I have contributed to this repository under the new open source license which will be decided by this thread.

**Comment by ihnorton** [comment]
For the record, I agree to relicense all the content I have contributed to this repository under the new open source license which will be decided by this thread.

**Comment by StefanKarpinski** [comment]
Ok, now we need to pick a license. How about dual license: MIT + some CC documentation license?

Also, I'm going to reserve rights to the logo for now – the logo may affect trademark issues, so I don't want to jump into that without getting legal advice first.

**Comment by johnmyleswhite** [comment]
I also relicense my content under whatever license we choose.

**Comment by timholy** [comment]
For the record, I agree to relicense all the content I have contributed to this repository under the new open source license which will be decided by this thread.

**Comment by one-more-minute** [comment]
For what it's worth, I consent to my work in this repo being relicensed in howeversuchway as is thought best in this thread.

**Comment by StefanKarpinski** [comment]
We need to pick a license. I'm in favor of using the MIT license to keep things simple – it covers "this software and associated documentation files", which in this case is mostly documentation and only a little code, but it seems applicable all the same. IIRC, when I chatted with Bradley Kuhn about licenses at the GSoC reunion thing, he said that the MIT license was fine for documentation too.

**Comment by hunterowens** [comment]
:+1: to MIT, inline with Julia's other projects.

Also, since the docs are MIT licensed, it doesn't make sense to have a seperate content license only for the website. If the docs had a license that was different, I would say use that.

**Comment by Carreau** [comment]
MIT sounds fine and everyone agrees to whatever will be chosen by the core member of julia. So is the approval of anyone else needed ?

**Comment by StefanKarpinski** [comment]
No, I just figured I'd give people a chance to comment.

**Comment by Carreau** [comment]
Then I would write an explicit deadline, like "if you have not commented by Truesday, 37th Marchuary  2095, we will assume you agree with MIT licence".

**Comment by StefanKarpinski** [comment]
That doesn't actually help legally. Not commenting does not qualify as granting a license.

**Comment by jiahao** [comment]
MIT is fine by me. I think just about everyone else who has commented has said they will agree with the final decision.

**Comment by simonster** [comment]
For the record, I agree to relicense all the content I have contributed to this repository under the new open source license which will be decided by this thread.

**Comment by domluna** [comment]
For the record, I agree to relicense all the content I have contributed to this repository under the new open source license which will be decided by this thread.

**Comment by rgbkrk** [comment]
For the record, I agree to relicense all the content I have contributed to this repository under the new open source license which will be decided by this thread.

MIT is good to me. Yay Julia!

**Comment by WestleyArgentum** [comment]
For the record, I agree to relicense my contributions I have contributed to this repository under the new open source license which will be decided by this thread.

**Comment by mlubin** [comment]
Does this include the blog posts? (Since I have one on julialang.org.) I don't want to be the one to hold things up, but what does it mean for a blog post to be MIT licensed?

**Comment by garrison** [comment]
For the record, I agree to relicense my contributions I have contributed to this repository under the new open source license which will be decided by this thread.

**Comment by quinnj** [comment]
For the record, I agree to relicense my contributions I have contributed to this repository under the new open source license which will be decided by this thread.

**Comment by mykelk** [comment]
For the record, I agree to relicense my contributions I have contributed to this repository under the new open source license which will be decided by this thread.

**Comment by vchuravy** [comment]
For the record, I agree to relicense all the content I have contributed to this repository under the new open source license which will be decided by this thread.

Although I feel that a Creative Commons license especially (CC BY 4.0) would be better suited for a website, then a license meant for code.

**Comment by sbromberger** [comment]
For the record, I agree to relicense all the content I have contributed to this repository under the new open source license which will be decided by this thread.

**Comment by garrison** [comment]
I also have considered that a free Creative Commons license might make more sense, potentially with the exception that any code snippets are licensed under MIT.  But then this is more complicated.  From what I can father from the Software Freedom Law Center's [Legal Issues Primer](http://www.softwarefreedom.org/resources/2008/foss-primer.html#x1-120002.4), the MIT License is likely to be just fine for the web site.

**Comment by ivarne** [comment]
For the record, I agree to relicense all the content I have contributed to this repository under the new open source license which will be decided by this thread.

**Comment by chezou** [comment]
For the record, I agree to relicense all the content I have contributed to this repository under the new open source license which will be decided by this thread.

**Comment by ajkl** [comment]
For the record, I agree to relicense all the content I have contributed to this repository under the new open source license which will be decided by this thread.

**Comment by scw** [comment]
For the record, I agree to relicense my contributions I have contributed to this repository under the new open source license which will be decided by this thread.

**Comment by simonster** [comment]
I suppose I would slightly prefer the CC-BY license, because the attribution requirement might be a good thing if a spam site or other nefarious party decides to copy the website or a large proportion of it wholesale.

**Comment by Ismael-VC** [comment]
For the record, I agree to relicense all the content I have contributed to this repository under the new open source license which will be decided by this thread.

**Comment by XieConnect** [comment]
For the record, I agree to relicense all the content I have contributed to this repository under the new open source license which will be decided by this thread.

**Comment by mauro3** [comment]
For the record, I agree to relicense all the content I have contributed to this repository under the new open source license which will be decided by this thread.

**Comment by i2000s** [comment]
Based on my simple search on legal issues of website licenses, I think both MIT and Creative Commons should work fine, and have similar effects on blog posts. Since the manual of Julia seems having been integrated as a part of the website,  it might be good to find a consistent license for all Julia's documentations in a long run. 

BTW, since I raised this request to use the website content earlier, I have directed this discussion to all contributors of JuliaLang.github.com who have their email addresses visible online. Not contacted are @wbhart, stevengj (I assume Steven knows it). Thanks for everyone's comments and efforts on this issue.

**Comment by kalaidin** [comment]
For the record, I agree to relicense all the content I have contributed to this repository under the new open source license which will be decided by this thread.

**Comment by macd** [comment]
For the record, I agree to relicense my contributions I have contributed to this repository under the new open source license which will be decided by this thread.

**Comment by DominikHolenstein** [comment]
For the record, I agree to relicense my contributions I have contributed to this repository under the new open source license which will be decided by this thread.

**Comment by tlycken** [comment]
If I read the commit log correctly, my only contribution was to *remove* content... :P Nonetheless:

For the record, I agree to relicense all the content I have contributed to this repository under the new open source license which will be decided by this thread.

**Comment by thomie** [comment]
For the record, I agree to relicense all the content I have contributed to this repository under the new open source license which will be decided by this thread.

**Comment by dcjones** [comment]
For the record, I agree to relicense all the content I have contributed to this repository under the new open source license which will be decided by this thread.

**Comment by TPieciak** [comment]
For the record, I agree to relicense all the content I have contributed to this repository under the new open source license which will be decided by this thread.

**Comment by lruthotto** [comment]
For the record, I agree to relicense my contributions I have contributed to this repository under the new open source license which will be decided by this thread.

**Comment by jakebolewski** [comment]
For the record, I agree to relicense all the content I have contributed to this repository under the new open source license which will be decided by this thread.

**Comment by palango** [comment]
For the record, I agree to relicense my contributions I have contributed to this repository under the new open source license which will be decided by this thread.

**Comment by llimllib** [comment]
I didn't even know I modified anything, but...

I agree to relicense all the content I have contributed to this repository under the new open source license which will be decided by this thread.

**Comment by dalexander** [comment]
For the record, I agree to relicense all the content I have contributed to this repository under the new open source license which will be decided by this thread.

**Comment by mbaz** [comment]
For the record, I agree to relicense all the content I have contributed to this repository under the new open source license which will be decided by this thread.

**Comment by ViralBShah** [comment]
Can we go ahead and merge this  - with the MIT license?

**Comment by StefanKarpinski** [comment]
We need @JeffBezanson to agree to the MIT license.

**Comment by mlubin** [comment]
Can I stick a CC-BY on my blog post? I agree to relicense all other content I have contributed.

**Comment by IainNZ** [comment]
I agree to whatever is required :)

**Comment by eford** [comment]
For the record, I agree to relicense my contributions I have contributed to
this repository under the new open source license which will be decided by
this thread.

On Thu, Mar 5, 2015 at 6:47 AM, mbaz <notifications@github.com> wrote:

> For the record, I agree to relicense all the content I have contributed to
> this repository under the new open source license which will be decided by
> this thread.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaLang/julialang.github.com/pull/204#issuecomment-77375723>
> .
>



-- 
Eric Ford
Professor of Astronomy & Astrophysics
Center for Exoplanets & Habitable Worlds
Center for Astrostatistics
Institute for CyberScience
Penn State Astrobiology Research Center
Pennsylvania State University

**Comment by StefanKarpinski** [comment]
@mlubin – Yes, we should add a clause to the site license saying that all content is MIT unless otherwise stated, in which case it is licenced under whatever license is indicated. So people can write their own blog posts and put e.g. a CC-BY license on it.

**Comment by StefanKarpinski** [comment]
To that end, if you've written a blog post on julialang.org and want it under a particular license, please go ahead and make a pull-request to put that license on it.

**Comment by rsrock** [comment]
For the record, I agree to relicense all the content I have contributed to this repository under the new open source license which will be decided by this thread.

**Comment by Ivo-Balbaert** [comment]
For the record, I agree to relicense my contributions I have contributed to this repository under the new open source license which will be decided by this thread.

**Comment by Keno** [comment]
Yep, I'm fine with any license chosen here for my contributions to this repository.

**Comment by nolta** [comment]
For the record, I agree to relicense my contributions I have contributed to this repository under the new open source license which will be decided by this thread.

**Comment by carlobaldassi** [comment]
For the record, I agree to relicense all the content I have contributed to this repository under the new open source license which will be decided by this thread.

**Comment by danking** [comment]
For the record, I agree to relicense all the content I have contributed to this repository under the new open source license which will be decided by this thread.

**Comment by hunterowens** [comment]
For the record, I agree to relicense all the content I have contributed to this repository under the new open source license which will be decided by this thread.

**Comment by aviks** [comment]
For the record, I agree to relicense all the content I have contributed to this repository under a new open source license which will be decided by this thread.

**Comment by HarlanH** [comment]
For the record, I agree to relicense all the content I have contributed to this repository under the new open source license which will be decided by this thread.

**Comment by tkelman** [comment]
For the record, I agree to relicense all the content I have contributed to this repository under the new open source license which will be decided by this thread.

**Comment by JeffBezanson** [comment]
I agree to license content I have contributed to this repository under the MIT license.

**Comment by markhend** [comment]
For the record, I agree to relicense all the content I have contributed to this repository under the new open source license which will be decided by this thread.

**Comment by waldyrious** [comment]
For the record, I agree to relicense all the content I have contributed to this repository under the new open source license which will be decided by this thread.

**Comment by Alexander-N** [comment]
For the record, I agree to relicense my contributions I have contributed to this repository under the new open source license which will be decided by this thread.

**Comment by StefanKarpinski** [comment]
Thanks, everyone!

**Comment by nalimilan** [comment]
A bit late to the party:

For the record, I agree to relicense my contributions I have contributed to this repository under the new open source license which will be decided by this thread.

**Comment by RhysU** [comment]
For the record, I agree to relicense all the content I have contributed to this repository under the new open source license which will be decided by this thread.

**Comment by jasax** [comment]
For the record, I agree to relicense all the content I have contributed to this repository under the new open source license which will be decided by this thread.

**Pull request merged**
