### PR TITLE
Group GSoC Projects by themes

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
This PR breaks up the giant " Scalability of technical computing for big data applications" into smaller and more mangagable themes. That main theme is still there for holding projects which did not fit in other places (and it makes sense: what's there is now SIMD, threading, and parallelism). 

Numerical optimization was pulled out to its own theme. I also made a theme which I called "Base Mathematics Libraries" for:

- Upgrading openlibm
- Special functions
- Matrix functions
- Fast bignums in Julia
- Random number generation

Maybe there could be a better name for this theme?

Also, the data related projects were moved to a theme "Data Handling".

Together, I think this makes it easier to navigate. Note that this is branched off of https://github.com/JuliaLang/julialang.github.com/pull/467, so it would require that first.

### CODE REVIEW

**Comment by ViralBShah** [comment]
Much of the openlibm work is being done by @musm and we should refer to that.

**Comment by ViralBShah** [comment]
I can merge this when ready.

**Comment by ChrisRackauckas** [comment]
Yes, I think the OpenLibm stuff should change to being about Amal.jl and @musm's work, but I am doing the PRs one at a time to hit different points. This one is about changing the groupings. Another will focus on updating the text for the OpenLibm parts.

Should potential mentors also be added (in a separate PR)?

**Comment by ViralBShah** [comment]
Makes sense. These projects have accumulated over time, and when we get close to GSoC again, we can refresh for being current and potential mentors. Let's just do the reorganization for now.

**Comment by ChrisRackauckas** [comment]
Fixed merge conflicts and ensured that the spacing/capitalizations used in different themes are the same.

**Pull request merged**
