### PR TITLE
gsoc section: Data Structure Algorithm Improvements

### PR DESCRIPTION
**Pull request by vtjnash**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Every project needs recommended skills, expected results, and mentors who would be willing.

**Comment by shashi** [comment]
@vtjnash edited to add skills and mentors. Hit merge if it's OK

**Comment by vtjnash** [comment]
I'm probably not a good mentor for this. If nobody volunteers their name here, it's probably best to leave this in PR state.

**Comment by MikeInnes** [comment]
This project is pretty general; we likely don't need the world's foremost data structure expert to mentor it. Let's leave it without a mentor and we can try to match a good student with someone who's free.

**Pull request merged**
