### PR TITLE
julia.bat is no more

### PR DESCRIPTION
**Pull request by PallHaraldsson**
I'm assuming julia.exe ..

### CODE REVIEW

**Comment by tkelman** [comment]
Not quite, there's no julia.exe in the top-level install folder (it's under bin/julia.exe), but there is a julia shortcut.

**Comment by PallHaraldsson** [comment]
I hope the test is ok and ok not to squashing the commits.. I think I'll figure out rebase and squash (I need  to for elsewhere, it seems I need git from the shell, with github.com not having some user interface..).

**Comment by tkelman** [comment]
remove the parenthetical, it's not really necessary

**Comment by tkelman** [comment]
I meant remove the note that was inside the parenthetical, not just the () around it. Most users don't need to worry about the fact that the shortcut points to bin/julia.exe.

**Comment by PallHaraldsson** [comment]
@tkelman I could do that.

I think the shortcut is only useful to start Julia/the REPL. I actually will be experimenting with running Julia scripts on Windows (machine I have to borrow..). In Linux #!/bin/julia takes care of running scripts. I noticed to run a script in Windows the extension .jl doesn't trigger running the program. Maybe I did something wrong (I know I could probably register the extension, but should I need to).

Anyway, I assume in Windows you would do:

[maybe longer path]bin/julia.exe my_script.jl

would it not help just to have it in? I think you can not do julia.shortcut [or whatever] my_script.jl.

Yes, most users would know this or?

**Comment by tkelman** [comment]
Windows doesn't do shebangs for script execution. So you can create your own shortcuts if you'd like.

The grammar is also wrong, should be its not it's.

**Comment by tkelman** [comment]
Closed by f2e4dc5471f106404c1e69b6cbd0412f85be0a34. These are basic "getting started" instructions, we can discuss creating your own shortcut and making use of `bin/julia.exe` somewhere else.

**Pull request closed without merging**
