### PR TITLE
Move downloads links to fastly-cached links

### PR DESCRIPTION
**Pull request by staticfloat**
@tkelman

### CODE REVIEW

**Comment by tkelman** [comment]
apparently the nightlies on this page still link to status.julialang.org?

**Comment by staticfloat** [comment]
Yes, I figured one change at a time was enough; let's not change that until we get https://github.com/JuliaLang/julia/pull/18554 settled

**Comment by tkelman** [comment]
Okay. And thanks for saving me the rebase, didn't even realize at first that this was against my branch.

Last one on my list is pkgdev then for newly registered packages, unless you don't care much about them?

**Comment by staticfloat** [comment]
pkgdev done

**Comment by tkelman** [comment]
I meant pkgdev.generate, not just its own appveyor (thought that would have been covered by your script?)

**Comment by staticfloat** [comment]
Yeah, I'm not sure what I was thinking.  I went into the repository and just got immediately distracted with the lack of a pull request to the usual appveyor.  I'm now doubting that the script caught them all, because I only opened ~400 PRs, but last I checked, it should have been closer to 600, so something must have gone wrong somewhere.

**Comment by tkelman** [comment]
did you get rate-limited maybe? either the presence of a branch on your fork or an open pr with the given title should be scriptable to find out which got missed, I'd think?

**Comment by tkelman** [comment]
657 registered packages have an appveyor.yml and two have an .appveyor.yml by my count

**Pull request merged**
