### PR TITLE
GSOC2017 JQ

### PR DESCRIPTION
**Pull request by jamesonquinn**
Blog post about my GSOC

### CODE REVIEW

**Comment by ararslan** [comment]
cc @bdeonovic for review

**Comment by ararslan** [comment]
Great, thanks. The image should be in `images/blog/2017-08-28-GSOC-MCMC-with-flexible-numbers-of-parameters/`. Once that's done this should be good to go.

**Comment by bdeonovic** [comment]
Ah thanks @jamesonquinn can you update?

**Comment by jamesonquinn** [comment]
I'm sorry, what are you asking for? An update of the blog post, or an
update about the status of the blog post, or what?

2017-09-02 17:38 GMT-04:00 Benjamin Deonovic <notifications@github.com>:

**Comment by bdeonovic** [comment]
Please move the image to the correct location as specified by @araslan

**Comment by jamesonquinn** [comment]
OK, done.

**Comment by ararslan** [comment]
Perfect, thanks!

**Comment by ViralBShah** [comment]
This post needs a newer date.

**Comment by ViralBShah** [comment]
Done.

**Comment by ararslan** [comment]
Sorry, I missed that. Thanks for taking care of it, Viral.

**Pull request merged**
