### PR TITLE
add a course at Óbuda University (Budapest, Hungary)

### PR DESCRIPTION
**Pull request by krisztiankosi**

### CODE REVIEW

**Comment by ViralBShah** [comment]
Does the course have a homepage? Would be nice to have it here.

**Comment by krisztiankosi** [comment]
Sorry, no homepage yet, but I have github repos, for examples, and another github repo, where I develop a toolbox, which helps to use a nonlinear control method (that is the heart of the courses, just in Fund.Math. we will cover the math of the nonlinear systems, and use that method just an example, in Int. Dev. Tools is concentrate mostly on  technique.

What is your suggestion: it will helps to add that two repos, and if yes, which form ?
the toolbox:
https://github.com/krisztiankosi/FPTControl.jl 
and the examples:
https://github.com/krisztiankosi/Control

I'm relatively new in the University, that's why I don't have homepage, yet. Hope it will be change in the future.

**Comment by PallHaraldsson** [comment]
Just note it's Hungary, I could not confirm two r-s in any language (Magyarország seems to be it natively), and I believe I can't change the title.

What has made it to the page is correct, just pointing out, and also other entries have links that gove 404, e.g.:

https://github.com/krisztiankosi/julialang.github.com/blob/master/teaching/www.luiss.it

**Comment by krisztiankosi** [comment]
Sorry, the typo in the Title is my foult. It is Hungary.  I changed it.

the 404 page is interesting, the links in my original was:

[Óbuda University](https://www.uni-obuda.hu), [John von Neumann Faculty of Informatics, Institute of Applied Mathematics](http://nik.uni-obuda.hu)

I can't see your link there. Where you found that ?

**Comment by ViralBShah** [comment]
I am merging this now. You can always update with course pages when you have them. Thanks for the PR.

**Comment by krisztiankosi** [comment]
Thank you.

**Pull request merged**
