### PR TITLE
add GSoC 2017: Parallelism in BioJulia

### PR DESCRIPTION
**Pull request by bicycle1885**
cc: @shashi

### CODE REVIEW

**Comment by shashi** [comment]
Great write up! Especially like the benchmark chart. Very meticulous in your approach as always.

@ararslan I'm fine with merging this.

**Comment by ararslan** [comment]
Great. Nice work, Kenta! Does the date have to be updated to reflect the merge date (presumably today)? @ViralBShah

**Comment by ViralBShah** [comment]
@ararslan Feel free to update the date and merge, or wait for @bicycle1885 to do it.

**Comment by ararslan** [comment]
Okay, I can take care of it. In general should the date of the post reflect the date the PR was merged?

**Comment by ViralBShah** [comment]
Yes, best to reflect the date the PR is merged, so that on the blog it shows up as the latest post, and as other sources pick it up, they know it is new material.

**Comment by ararslan** [comment]
Hm, I pushed a commit to Kenta's branch but it doesn't seem to have updated the PR. I'll try closing and reopening.

**Comment by ararslan** [comment]
Okay, that got one commit but I had to push another to update a link. Let's try this again. Sorry for the close/reopen spam, Kenta.

**Pull request merged**
