### PR TITLE
Add reference to julia and julia-coverage chat rooms.

### PR DESCRIPTION
**Pull request by Ismael-VC**
* https://gitter.im/JuliaLang/julia
* https://gitter.im/kshyatt/julia-coverage

### CODE REVIEW

**Comment by ihnorton** [comment]
:-1:

**Comment by ViralBShah** [comment]
Why?

**Comment by Ismael-VC** [comment]
@ViralBShah thanks!

@ihnorton yeah ...why?

**Comment by ihnorton** [comment]
The main issue is fragmentation: I don't really see the point of three (English language) chat rooms. Gitter or IRC: let's pick one and use it. Gitter has an IRC server, so people who like IRC could just switch servers if we switch to Gitter completely.

Also, Gitter is proprietary, but whatever -- so is GitHub. The difference is that GitHub isn't going anywhere, but we'll all be back on freenode as soon as Atlassian or HipSlack or the latest SaaS hotness buys Gitter out.

**Comment by ViralBShah** [comment]
Ping @tkelman @kshyatt 

BTW, I am ok with a decision any ways.I don't prefer to have much over chat, and prefer issues since the discussion at least stays archived systematically.

**Comment by kshyatt** [comment]
I don't have a strong opinion either. My experience so far on Gitter has been that people with open PRs/issues are more willing to pop in and ask something/chat a bit than they are on IRC, because they are already on Github. Maybe GitHub will buy Gitter and obviate this problem.

**Comment by Ismael-VC** [comment]
They are just tools and they have been chosen by the community, this page is for the community and of course that grows organically.

> I don't prefer to have much over chat, and prefer issues since the discussion at least stays archived systematically. 

Not everyone thinks that way: https://github.com/JuliaLang/julia/issues/11885#issuecomment-118989448

> I mostly made this room to address Kristoffer's complaints about people using Github issues as chat rooms - @kshyatt

**Comment by kshyatt** [comment]
I guess if we don't want to use Gitter (I don't like proprietary software either, @ihnorton), we should clamp down harder on people making off-topic/white-noise/"chat" comments - I've been guilty of doing this - on GitHub and politely but firmly direct them to IRC more than we have.

**Comment by ihnorton** [comment]
Sorry for stirring this up. Pointing everyone to one Gitter room would be fine IMHO; I'm mostly against fragmentation because it is confusing to newcomers and runs a risk of rooms fading over time.

Anyway, the Gitter interface and integration are certainly good, and people like nice, simple-to-use things (IRC is neither, by default). We could potentially even set up a bridge to the old channel.

**Comment by Ismael-VC** [comment]
I think people is more willing to chat and stay around at Gitter since it supports unlimited scroll back history, inline gist snippets, nice smartphone apps, syntax highlighting, it integrates well with GitHub among many other things that irc does not. This lets people see what's been up. While the irc channel seems desertic in comparison most of the time.

**Comment by quinnj** [comment]
+1 to focusing all "chat" functionality to a single channel/room. I've liked Gitter when I've poked around it in the past, but I've also not seen these chat rooms gain a lot of traction. Perhaps as the community grows, there will be more interest though.

**Comment by Ismael-VC** [comment]
IRC first impression to new comers, from the link provided in this community page:

captura de pantalla 2015-07-07 a las 23 41 20

Gitter first impression:

captura de pantalla 2015-07-07 a las 23 43 56

**Comment by kshyatt** [comment]
Maybe people being greeted by my face is an argument for IRC. I see people filter through IRC who ask a question then vanish into the ether who probably wouldn't log into Gitter.

**Comment by Ismael-VC** [comment]
There are a lot of rooms now around 10 of them are used a lot too:

captura de pantalla 2015-07-07 a las 23 48 37

I count at least 32 of them so far:

* https://gitter.im/explore/tags/julia

**Comment by Ismael-VC** [comment]
@ihnorton where you see fragmentation I see diversification.

**Comment by ihnorton** [comment]
I don't really care about the *existence* of other rooms, just the long-term viability and usefulness of the link(s) that new users see here. Anyway, FWIW, I would vote to unify the 3 English language chat rooms to one Gitter. Having said that, I desist.

**Comment by Ismael-VC** [comment]
I prefer  Gitter over IRC and Gitter can be used from IRC for the people that prefer IRC, but not the other way around.

I agree that it would be useful to merge Julia IRC and Julia Gitter rooms (at Gitter), but leave julia-coverage apart, since this room has an specific purpose (I bet more specific purpose rooms would be also useful) while Julia room is more generic.

But that's just me.

**Pull request merged**
