### PR TITLE
Develop an AI package in Julia based on AIMA

### PR DESCRIPTION
**Pull request by sambitdash**
AI requires well defined definitions to be effectively develop applications. AIMA frameworks can benefit practitioners in designing their problems better. Such a framework is not offered by any other libraries today.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
This is far too detailed. It should be just a short paragraph summary. Also this needs mentors. @sambitdash are you agreeing to mentor?

**Comment by ChrisRackauckas** [comment]
Also, this is written in the first person "an attempt has been made by me". It repeats a lot of things already written into the application materials like how much Julia knowledge is required, and just doesn't match the format of the others. This should get reverted and reworked to be like the other projects.

**Comment by ViralBShah** [comment]
Shorter as discussed and avoiding first person would be nice to have, but I prefer not to revert. I do agree about the mentorship.

@sambitdash Would you be willing to mentor?

**Comment by sambitdash** [comment]
Ok let me fix the write up and the mentor section and resubmit with another PR. I can be the mentor.  But if there is someone more experienced interested happy to delegate as well.

**Pull request merged**
