### PR TITLE
Fix oldreleases.md formatting and update wording

### PR DESCRIPTION
**Pull request by staticfloat**

### CODE REVIEW

**Comment by tkelman** [comment]
lgtm, merge if you trust the rendering

**Comment by tkelman** [comment]
Darn, the markdown looks fine but the html still isn't coming out right for v0.2.1... I guess just go ahead and push tweaks until one comes out correctly?

**Comment by staticfloat** [comment]
Got'em, coach.

**Comment by tkelman** [comment]
Yep, looks good now, thanks! Why so finicky, web stuff?

**Pull request merged**
