### PR TITLE
Add mention of the Julia Computing blog on the Blog page

### PR DESCRIPTION
**Pull request by nalimilan**
There have been very interesting posts there recently.

### CODE REVIEW

**Comment by ViralBShah** [comment]
The Julia Computing Blog was registered with juliabloggers.com just a couple of days ago. We have a few more coming, and hope to keep it up - and will also be publishing more blogs on the julialang blog.

**Comment by nalimilan** [comment]
Yes, I've seen that, but I thought it deserved a specific mention as posts are really of the same level as those on the Julia blog. They shouldn't be lost along all other blog posts.

**Comment by jiahao** [comment]
:+1: for mentioning the Julia Computing blog.

Perhaps the wording could be improved so that it's clear that the company is not the sole source of "ongoing Julia development" (although no doubt an important source).

**Comment by ViralBShah** [comment]
Good point - I think it should just say: See also the Julia Computing blog, and leave it that.

**Comment by nalimilan** [comment]
I'd prefer keeping the explicit formulation about what kind of posts one can expect on that blog. What do you think of the new version?

**Comment by ViralBShah** [comment]
I think its good.

**Pull request merged**
