### PR TITLE
add link to discourse page

### PR DESCRIPTION
**Pull request by simonbyrne**

### CODE REVIEW

**Comment by ViralBShah** [comment]
Cc @vchuravy @StefanKarpinski

**Comment by StefanKarpinski** [comment]
Sure, although it might be a little early since we haven't moved julia-users over yet.

**Comment by simonbyrne** [comment]
I've purposely left julia-users there, with the intention that it be removed when the final move is made. It seems odd though to leave julia-dev and julia-stats up.

**Comment by StefanKarpinski** [comment]
Yeah, fair enough.

**Pull request merged**
