### PR TITLE
add diffeq paper

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
Adds the new publication on DifferentialEquations.jl's adaptive method for stochastic differential equations: http://aimsciences.org/journals/pdfs.jsp?paperID=14010&mode=full

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Can someone merge the other citation PRs as well? I don't think I should run Jekyll until those are all merged in, right? I can merge them all on my own fork and make a PR which updates index as well, should I be doing that?

**Comment by ViralBShah** [comment]
Ok merged all the others. I feel that we should just move to a simple markdown file here. Perhaps try to leverage google scholar and other tools more.

**Comment by ChrisRackauckas** [comment]
Well, I tried running the makefile but I got:

```julia
[crackauc@crackauc2 publications]$ make
PATH=/usr/lib64/qt-3.3/bin:/usr/local/heroku/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/usr/local/cuda/bin:/home/crackauc/.local/bin:/home/crackauc/bin:/usr/local/cuda/bin:~/.cabal/bin pandoc --reference-links -s -S --biblio julia.bib --csl jlwebpage.csl -o index_new.html _EDIT_ME_index.md
pandoc-citeproc: error while parsing the XML string
pandoc: Error running filter pandoc-citeproc
make: *** [all] Error 83
```

If someone could show me how to get the line number for what's wrong out of that I'd be happy to help out with this in the future. But that's giving me nothing to go off of. Note that I merged https://github.com/JuliaLang/julialang.github.com/pull/561 into this PR since I was just going to build the index with all of the current publications (but failed).

**Comment by ChrisRackauckas** [comment]
>I feel that we should just move to a simple markdown file here. Perhaps try to leverage google scholar and other tools more.

I definitely agree. Maybe we should discuss this in https://github.com/JuliaLang/julialang.github.com/issues/421

**Comment by simonbyrne** [comment]
Do you want to update this for the new publication format? Hopefully it should be clear, but let me know if you have any questions.

**Comment by ChrisRackauckas** [comment]
I think it's easier just to do it as a new PR

**Pull request closed without merging**
