### PR TITLE
move publication list to jekyll collection

### PR DESCRIPTION
**Pull request by simonbyrne**
This gets rid of the cumbersome bibtex process for adding publications. Now you just add a file to the _publications directory and the result should be formatted nicely.

I don't think we should display the abstracts by default, but I've kept the existing abstract data around in case we want to have some way to display it in future (this is beyond my HTML skills). We could also create a template to generate bibtex as well if we wanted.

### CODE REVIEW

**Comment by simonbyrne** [comment]
Also, this gets rid of the "</body> </html>" at the bottom of the current publications page.

**Comment by ChrisRackauckas** [comment]
This looks great!

**Comment by ViralBShah** [comment]
@simonbyrne Merge when ready! We can tweak as we go along.

**Comment by simonbyrne** [comment]
Now live: https://julialang.org/publications/

**Pull request merged**
