### PR TITLE
add Gemfile and small reformat of readme

### PR DESCRIPTION
**Pull request by dancinglightning**
just made the readme a little more readable, no real change, just formatting
Gemfile as per issue #307

### CODE REVIEW

**Comment by pao** [comment]
LGTM, thanks!

**Comment by ViralBShah** [comment]
Do we need the Gemfile.lock?

**Comment by dancinglightning** [comment]
While the Gemfile says which gems u uses, the lock file says which versions are actually used.
Checking it in means everyone uses the same versions and the maintainer does not have to chase weird bugs that come from using different versions.
i'd go with yes :-)

**Comment by ViralBShah** [comment]
Thank you for the explanation. I was just wondering if it was a temporary lockfile that got checked in by mistake.

**Pull request merged**
