### PR TITLE
RFC: draft of jsoc announcement

### PR DESCRIPTION
**Pull request by mlubin**
As requested by @ViralBShah.

Should we set up an email group (a la juliacon) to manage inquiries and submissions?

### CODE REVIEW

**Comment by ViralBShah** [comment]
+1 on a juliasoc mailing list!

**Comment by mlubin** [comment]
Just thinking now, should this be a private list for organizers or a public list for everyone?

**Comment by ViralBShah** [comment]
For experienced Julia contributors, we can still have them in JSOC, but they would still need a mentor - just as someone to approve that the work was done. Do we need to mention this separately?

**Comment by mlubin** [comment]
Yes, that's here:
> If you're already a contributor to Julia or a Julia package and want to get paid to continue an existing project, that's okay too! In this case we still ask you to find a mentor who's familiar with your field of work.

**Comment by mlubin** [comment]
We can tweak the wording of course

**Comment by ViralBShah** [comment]
Thanks. The wording is fine.

Actually, we also do not need to restrict to students. All are welcome, so long as they can spend a good chunk of time doing the projects that they submit - with preference for students.

**Comment by mlubin** [comment]
Are there any official qualifications then? I'm assuming we can't fund people based in Cuba or Iran

**Comment by ViralBShah** [comment]
Not at the moment. We will have to check with NF. Do you know what GSOC says on this?

**Comment by ViralBShah** [comment]
I think we should put something generic here about selections being made in conformance to applicable Government laws.

What do you think about also adding `jsoc` to the menu items on the top, and also an advertisement next to the juliacon one?

**Comment by mlubin** [comment]
Updated with menu item and working email link. Should be mergeable.
I'll let someone with better web skills set up an add next to the juliacon link.

**Pull request merged**
