### PR TITLE
Update download links for 0.6.0-rc3

### PR DESCRIPTION
**Pull request by tkelman**

### CODE REVIEW

**Comment by ararslan** [comment]
Looks like the macOS link still downloads rc2?

**Comment by ChrisRackauckas** [comment]
Windows still downloads rc2

**Comment by tkelman** [comment]
oh right, the cache needs an hour to update the -latest file

**Comment by tkelman** [comment]
@staticfloat what did you say the api was to force fastly to invalidate the cache of something? could you write that down in https://github.com/JuliaLang/julia/blob/master/contrib/prepare_release.sh ?

**Comment by staticfloat** [comment]
Cache invalidation should only be needed if the file contents have changed while the filename has not.

To invalidate a single file, just `curl -X PURGE http://julialang-s3.julialang.org/foo`.  Are you thinking we just tag those onto the end of `prepare_release.sh` and auto-invalidate everything we just uploaded?

**Comment by tkelman** [comment]
just need to invalidate the 0.6-latest files that are expected to get updated in-place

**Comment by staticfloat** [comment]
Ah, yeah, that makes perfect sense.

**Comment by GlenHertz** [comment]
Linux x64 still downloads rc2 (eg https://julialang-s3.julialang.org/bin/linux/x64/0.6/julia-0.6-latest-linux-x86_64.tar.gz)

**Comment by tkelman** [comment]
I just manually ran the purge commands, try again

**Comment by ararslan** [comment]
Seems macOS is still rc2

**Comment by GlenHertz** [comment]
Win64 is good.

**Comment by GlenHertz** [comment]
Linux64 is good.

**Comment by ararslan** [comment]
macOS is good.

**Comment by ararslan** [comment]
Man, what's a guy gotta do to get a heart reaction emoji... 😛

**Comment by mkborregaard** [comment]
❤️

**Pull request merged**
