### PR TITLE
Added JuliaDelhi

### PR DESCRIPTION
**Pull request by rahulkp220**
Added juliadelhi's meetup information on line 245.

### CODE REVIEW

**Comment by rahulkp220** [comment]
@ararslan Can we add our Github, Facebook and twitter links as well? Let me know if adding all or any one of these is an option.

**Comment by ararslan** [comment]
I'm not sure what the policy on such links is, if any. @ViralBShah?

**Comment by ChrisRackauckas** [comment]
Those links are at the top of the Meetup page, so is it really necessary to copy them all over?

**Comment by rahulkp220** [comment]
@ChrisRackauckas yeah you are right, but I saw dedicated sections for Github and Twitter, which made me think. However, I am okay if those are reserved for official JuliaLang's repos and links.

**Comment by ChrisRackauckas** [comment]
>However, I am okay if those are reserved for official JuliaLang's repos and links.

Those aren't official. But most of those are only Github orgs, or only Twitter (channels?). I don't think anything else doubles up into multiple categories.

**Comment by rahulkp220** [comment]
I saw juliaLangEs (Mexico) and Julia Tokyo following similar route.

**Pull request merged**
