### PR TITLE
Update 0.6 download links to 0.6.1

### PR DESCRIPTION
**Pull request by ararslan**
I bless the rains down in Africa

### CODE REVIEW

**Comment by ViralBShah** [comment]
Does 0.6.0 go into older releases as part of this?

**Comment by ararslan** [comment]
I'm not sure. I thought we only did that for minor versions rather than patch versions but I don't actually know. I can put 0.6.0 there if you'd like.

**Comment by ViralBShah** [comment]
To answer my own question, it doesn't seem so. Unrelated, We should probably mark 0.5 as unmaintained though.

**Comment by ararslan** [comment]
Don't we typically (at least claim to) support bugfixes for the previous minor version? So when 0.7 is released, 0.5 would be unmaintained and 0.6 would be bugfix-only?

**Pull request merged**
