### PR TITLE
add a blog post of JSoC 2015 (@bicycle1885)

### PR DESCRIPTION
**Pull request by bicycle1885**
This is a draft of my blog post, I'm going to modify a little bit more this weekend.

A few questions:

* Where should I put image files? Now I put them in my Dropbox public folder, but there may be a better place.
* How can I check the rendered output? The README.md says I should run `bundle install`, but the bundle said `Could not locate Gemfile or .bundle/ directory` when I executed the command.

cc: @dcjones

### CODE REVIEW

**Comment by rohitvarkey** [comment]
@bicycle1885 Just create a file named `Gemfile` in the root directory of the repo with the contents as
```
source 'https://rubygems.org'
gem 'github-pages'
```

and then run `bundle install` and `jekyll serve`

**Comment by bicycle1885** [comment]
@rohitvarkey Thank you! I should have googled before asking...

**Comment by shashi** [comment]
Why not put the images under the images directory in this repo? (probably in a subdirectory)

**Comment by bicycle1885** [comment]
@shashi Thank you. I've added images under the images/blog/2015-10-03-sequence-analysis/ directory. Is this looks good?

**Pull request merged**
