### PR TITLE
Justify paragraphs.

### PR DESCRIPTION
**Pull request by Ismael-VC**
Justified alignment looks better IMHO.

After: 

captura de pantalla 2015-07-22 a las 15 34 52

Before:

captura de pantalla 2015-07-22 a las 15 35 37

Demo: http://julialanges.github.io

### CODE REVIEW

**Comment by pao** [comment]
This also uncenters the navigation bar. I don't think that was intended.

That side, I'm not convinced I like this any better. It makes the wall of text even more wall-like. But y'know, opinions.

**Comment by jiahao** [comment]
-1

Most typographers recommend against full justification of text. [This blog post](https://kaiweber.wordpress.com/2010/05/31/ragged-right-or-justified-alignment/) has a nice summary of the reasons why you shouldn't, as well as studies on the impact of full justification on decreased readability.

Furthermore, the W3C explicitly [recommends against full justification](http://www.w3.org/TR/WCAG20-TECHS/G169.html), stating:

> Many people with cognitive disabilities have a great deal of trouble with blocks of text that are justified (aligned to both the left and the right margins). The spaces between words create "rivers of white" running down the page, which can make the text difficult for some people to read. This failure describes situations where this confusing text layout occurs. The best way to avoid this problem is not to create text layout that is fully justified.

**Comment by johnmyleswhite** [comment]
Jiahao, I think you've got this backwards. I believe the PR tries to remove full justification.

**Comment by jiahao** [comment]
Derp. Thanks for spotting that.

**Comment by pao** [comment]
Er, what? The current text is not justified, it's ragged-right. The style added in the diff is `text-align: justify`. What am I missing?

**Comment by johnmyleswhite** [comment]
Is the original description wrong when showing before and after images?

**Comment by jiahao** [comment]
Yes the original description is wrong. I need caffeine.

**Comment by pao** [comment]
Ah, yeah, I didn't actually read the labels. They're wrong though so that didn't cost me anything.

**Comment by Ismael-VC** [comment]
Sorry the description is wrong, navigation bar can be centered like this:

* https://github.com/JuliaLangEs/julialanges.github.com/blob/master/_includes/links.html#L2

captura de pantalla 2015-07-22 a las 15 51 41


I think not justified text looks messy.

**Comment by Ismael-VC** [comment]
Oh the PR is closed, 

@jiahao The Julia web site is very simple, perhaps if it had more elements I would agree with you, but as it is right now it´s just the text and the white background, no visual style at all. 

I understand the "white river issue", but did you check the demo? I don´t see any unless I use a smartphone or a lot of zoom, but one way or another it looks ugly on a smartphone.

Anyway I'm glad accessibility is taken into account.

**Comment by jiahao** [comment]
Yes I did, and I did verify that you can quite easily find a browser window size that exhibits this 'river' illusion.

now:

screen shot 2015-07-22 at 5 29 37 pm

this pr:

screen shot 2015-07-22 at 5 29 27 pm

**Comment by Ismael-VC** [comment]
Ok, I see. Didn't consider that too much  I think that the thing that bothers me is that the web is too simple, do you know if there have been plans to redesign the web site?

I only found this: https://groups.google.com/forum/#!topic/julia-users/B5d-Wtp17GA

But they discuss content (which I know is more important) only.

**Comment by jiahao** [comment]
You can submit a PR and have people look at it. But a redesign has already been tried - see #178, which was ultimately reverted.

**Comment by Ismael-VC** [comment]
@jiahao thanks!

**Comment by jiahao** [comment]
@Ismael-VC see also #63

**Pull request closed without merging**
