### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by roding**
Have added publication RZRB16 to julia.bib and _EDIT_ME_index.md. Asking for help in recompiling.

### CODE REVIEW

**Comment by tkelman** [comment]
@jiahao do you have any guidance here?

**Comment by tkelman** [comment]
@jiahao however you have your notifications set up, please consider changing it so you don't completely ignore issues where you are mentioned directly. I realize you can't keep up with every issue these days, but you are still affiliated with the project right?

**Comment by jiahao** [comment]
Thanks for contributing. The easiest thing to do would be for me to update the list of publications offline.

**Comment by jiahao** [comment]
Publication list updated in ee6e2a2c7281d098e6ea45269c26a00495419d89

**Pull request merged**
