### PR TITLE
Update download links for v0.3.11

### PR DESCRIPTION
**Pull request by tkelman**
cc @staticfloat, I sorted out the buildbots and they're working on these now, once they're uploaded to julianightlies can you move over to the julialang bucket and merge? Thanks.

### CODE REVIEW

**Comment by staticfloat** [comment]
Oh good; any idea what was weird about them?

**Comment by staticfloat** [comment]
Moved over and checksums uploaded.

**Comment by tkelman** [comment]
Thanks! It turns out if you do something to the osx buildbots that causes gfortran to not be available, the "quickbuild" runs won't work correctly until you run at least one "package" build.

**Comment by staticfloat** [comment]
That is the kind of errata I wish we didn't have to know. :P

**Comment by tkelman** [comment]
That should be fixable by adding a few of the brew lines to the quickbuild steps, but they'd need to be conditional on darwin.

**Pull request merged**
