### PR TITLE
Create 2016-01-04-atom-work.md

### PR DESCRIPTION
**Pull request by one-more-minute**

### CODE REVIEW

**Comment by ViralBShah** [comment]
Looks great. Let's wait for a day for comments and merge?

**Comment by one-more-minute** [comment]
Sounds good, comments and feedback are very welcome of course.

**Comment by Ismael-VC** [comment]
I like it, I would like to suggest adding a screenshot.

**Comment by Varanas** [comment]
:+1: to screenshots. Maybe even some fancy animated gif? Might be a bit too much though.

**Comment by ViralBShah** [comment]
Animated GIFs would be cool but may be too much - but a screenshot would be great!

**Comment by Ismael-VC** [comment]
I like the GIF idea too!

**Comment by one-more-minute** [comment]
Sure thing – I have a gif at the [end of the post](https://github.com/JuliaLang/julialang.github.com/blob/one-more-minute-patch-1/blog/_posts/2016-01-04-atom-work.md) which comes from the atom-ink repo. Can replace with a screenshot if it seems like too much.

**Comment by Varanas** [comment]
Uhoh, reading comprehension really doesn't seem to be my strong suit... ;) Anyways, I think it may be a bit unfortunately positioned there at the end; a static image higher up would be a bit better imho.

**Comment by ViralBShah** [comment]
I moved the gif up top.

**Comment by one-more-minute** [comment]
Fair enough, thanks for the merge!

**Pull request merged**
