### PR TITLE
community: Update mailing list section

### PR DESCRIPTION
**Pull request by jayschwa**
* Added julia-news
* Changed URLs to a slightly shorter, nicer form
* Changed from paragraphs to an unordered list
* DRY'd out some of the wording and other small tweaks

### CODE REVIEW

**Comment by jayschwa** [comment]
I suggest locking down julia-news and making it read-only before merging this. It appears anybody can post to the list right now.

**Comment by StefanKarpinski** [comment]
That was the intention but I guess that replies could go to Julia-users or something like that.

**Comment by pao** [comment]
I think the intent with -news is that if it's not a Julia (pre-)release announcement, it doesn't belong there--sysadmins or folks who play them in their schools or offices would be likely to need to act on something posted there.

**Comment by jayschwa** [comment]
Right. There are plenty of other lists for discussions. This shouldn't be one of them. The model I had in mind was https://groups.google.com/group/golang-announce.

**Comment by StefanKarpinski** [comment]
I've changed it so that only managers and owners can post. I also made you a manager, Jay :-)

**Comment by jiahao** [comment]
Should the list be called `julia-announce` instead? I feel like I've seen `-announce` more frequently than `-news`.

**Comment by StefanKarpinski** [comment]
Already done and I don't really feel like making a new list.

**Comment by jayschwa** [comment]
I think I've seen "announcement" more too, but I doubt "news" will confuse anyone.

**Comment by ViralBShah** [comment]
Yes, `-announce` is more common, but no point creating a new one now. `-news` is perfectly fine.

**Comment by jayschwa** [comment]
Bump. We had our inaugural julia-news post, but the list still isn't mentioned on the site as far as I can tell.

**Pull request merged**
