### PR TITLE
Update ARM nightly link and rename it to ARMv7

### PR DESCRIPTION
**Pull request by yuyichao**
Remove "32bits" since that's implied by v7.

### CODE REVIEW

**Comment by tkelman** [comment]
I don't think everyone is going to know that, best to leave the 32 bit there.

**Comment by yuyichao** [comment]
Everyone that want to use the binary should know it. The v7 is also much more important than the 32bit.

**Comment by tkelman** [comment]
I'm in a room with a few dozen people who use these binaries every day, and in terms of what they're familiar with it's the exact opposite.

**Comment by tkelman** [comment]
will this also change binaries manually built from release-0.5? if so, then `contrib/prepare_release.sh` in the Julia repo will need to be updated (and backported) as well

**Comment by yuyichao** [comment]
Not sure what exactly you mean by "manually built from release-0.5" but the change is caused by using a newer gcc that's compiled for an armv7 triple. If you build any version manually using a compiler that gives you `arm-***` triple the name would be the same with what it was before.

**Comment by tkelman** [comment]
I mean the binaries built on the buildbot, including release binaries of forthcoming 0.5.x backports.

**Comment by yuyichao** [comment]
Then yes. Unless the compiler on the buildbot is recompiled with a different triple the new binaries will have armv7l in them by default.

**Comment by yuyichao** [comment]
Actually the name of the binary on http://julianightlies.s3.amazonaws.com/ didn't change so `prepare_release.sh` does not need to be changed. We'll want to differentiate them if/when we have v6/v8 binaries but that can happen later.

**Comment by ViralBShah** [comment]
Good to have the 32-bit in there. I didn't know that v7 was 32-bit only.

**Pull request merged**
