### PR TITLE
Delete CNAME

### PR DESCRIPTION
**Pull request by Ismael-VC**

### CODE REVIEW

**Comment by Keno** [comment]
Why?

**Comment by StefanKarpinski** [comment]
This file is necessary to tell GitHub that it should handle HTTP requests for the domain julialang.org.

**Comment by Ismael-VC** [comment]
I'm sorry I'm testing Transifex and I thougth I was making a PR to JuliaLangEs/julialanges.github.com

**Comment by yuyichao** [comment]
> I'm sorry I'm testing Transifex

@Ismael-VC Can I interpret this as you are trying to make the doc/website etc translateable on Transifex? It's not my favorate translating tool (I prefer editing locally) but it'll be so much better than manually syncing the manuals...

**Comment by Ismael-VC** [comment]
@yuyichao that's right, well I don't really know what would be a better translating tool, but I've been planning this for a long time, finally have time to implement ir and understand the platform better. but hey! I have a working demo, and Transifex Live is actually pretty cool and good at doing it's job! Would you mind trying it out please if you have some time?

https://www.transifex.com/projects/p/julia-web

This would only be for the web page, since I plan to use Crowdin for the documentation.

https://github.com/JuliaLang/julialang.github.com/pull/252

**Comment by yuyichao** [comment]
>  well I don't really know what would be a better translating tool

I personally prefer Lokalize (a KDE tool used by KDE) a little more but I would not suggest using it for julia for obvious reasons. Transifex is the best online tool (not that I've used many) I've used for collaboration on translation.

> I plan to use Crowdin for the documentation.

I've never used that one. What's the difference / advantage? The front page seems to suggest that it's not free?

**Comment by Ismael-VC** [comment]
Yeah at first I also tried to start with localize, but I don't want that translators need to setup anything! This is a good way for new julians to contribute. Whoever that wants to help on this should just worry about the quality of the translations and nothing else IMHO.

**Comment by Ismael-VC** [comment]
When I was testing the demo, the fantastic folks at transifex aproved the project as open source and gave us the platform for free! :sparkles: 

I was also able to activate Yandex machine aided translation support, and again Crowdin guys went even further and also activated Microsoft aided translation. This is something that costs in Transifex and we currently don't have. This is the primary advantage for using Crowdin for the documentation.

Yet Transifex Live is better for the Live auto updates for translating web pages.

**Comment by Ismael-VC** [comment]
Crowdin with bot Yandex and Microsoft computer aided translations:

captura de pantalla 2015-07-15 a las 19 21 02

Transifex Live with no computer aided translations :disappointed: : 

captura de pantalla 2015-07-15 a las 19 22 23

**Comment by Ismael-VC** [comment]
We should continue the discussion at: https://github.com/JuliaLang/julialang.github.com/pull/252

**Pull request closed without merging**
