### PR TITLE
Add Blog Post

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
I added the "7 Julia Gotchas and How to Handle Them" blog post. This post got a lot of reach, reblogged at Hacker News, Reddit, etc. and has gotten over 1,000 views, so since people are liking it I thought it should continue to be shared.

### CODE REVIEW

**Comment by johnmyleswhite** [comment]
I don't think we should start adding blog posts here.

**Comment by quinnj** [comment]
I don't know, it was a pretty popular blog post, so why not? I do understand though that it's a bit of a rabbit hole; why include this blog post but not every blog post about Julia? Perhaps we need a clearer distinction around "official" blog posts released from JuliaLang itself as an organization.

**Comment by ViralBShah** [comment]
While I think we should publish a wide variety of posts on the julia blog, I am not sure we should republish. juliabloggers.com does a good job of aggregating various julia related posts.

**Comment by kkaragul** [comment]
Teaching Julia in classroom:
Pamukkale University, Engineering College, Computer Engineering Department,
IENG 418	 SERVICE SYSTEMS, Dr. Kenan KARAGUL
Syllabus Page
https://ebs.pau.edu.tr/BilgiGoster/Ders.aspx?lng=2&dzy=3&br=21&bl=65&pr=167&dm=619&ps=3&dk=95116&ds=0

**Comment by ViralBShah** [comment]
@kkaragul Please submit a pull request to the blog. Writing in unrelated pull requests or issues will lead to the issue being lost.

**Pull request closed without merging**
