### PR TITLE
Update download links for v0.3.9

### PR DESCRIPTION
**Pull request by tkelman**
cc @staticfloat release full-source-dist tarball is up now, for updating the checksums

### CODE REVIEW

**Comment by staticfloat** [comment]
Checksums updated.

**Comment by tkelman** [comment]
Right-o. Tim Davis' website did not want this one to go through, but one way or another...

**Comment by staticfloat** [comment]
Hah.  Thanks for persevering.  :)

**Comment by tkelman** [comment]
I'm getting an access denied on the checksum files

**Comment by staticfloat** [comment]
Fixed.

**Comment by tkelman** [comment]
Thanks!

**Pull request merged**
