### PR TITLE
RFC: Add Transifex translation scripts.

### PR DESCRIPTION
**Pull request by Ismael-VC**
Ref: https://github.com/JuliaLang/julialang.github.com/issues/187

Working demo: http://julialanges.github.io

CC: @yuyichao

### CODE REVIEW

**Comment by Ismael-VC** [comment]
Translated demo page with Transifex widget at the bottom and language selector at the top rigth corner:

captura de pantalla 2015-07-15 a las 18 32 28

**Comment by Ismael-VC** [comment]
Transifex Live automatic sync and update interface:

captura de pantalla 2015-07-15 a las 18 37 39

**Comment by Ismael-VC** [comment]
The purpose of this is to avoid redundant duplication of efforts by each and every community that would like to provide translations for the Julia web page. Alternatively every non english speaking community would have to fiddle alone with the update and sync process and provide a satellite language specific clone of the web page or just have everyone roll out their own versions. IMHO this is very cool!

CC: @StefanKarpinski @JeffBezanson @ViralBShah @ivarne

**Comment by yuyichao** [comment]
Re: https://github.com/JuliaLang/julialang.github.com/pull/250#issuecomment-121788593 Agree

Do you know what access control does transifex (and Crowdin) has? Would be nice if new translators can submit suggestions for review without having full access. (just like PR's on github). I somehow remember that you can only translate sth on Transifex if you are a translator? Maybe I'm just using it wrong.

**Comment by Ismael-VC** [comment]
There is a staging and a production environment, several user roles with different permissions:

* http://docs.transifex.com/introduction/#user-roles-in-transifex
* https://www.transifex.com/blog/2014/introducing-team-managers

captura de pantalla 2015-07-16 a las 07 54 26

Also see: https://github.com/JuliaLang/julialang.github.com/issues/187#issuecomment-121947310

**Comment by waldyrious** [comment]
Can translation memory (suggestions from similar strings that have been previously translated) and machine translation be used with Transifex to assist translators? If not, as a user interested in helping with the translation and who has tried various platforms, I'd strongly recommend using Crowdin instead (more details on these advantages have been listed by @Ismael-VC in #250).

**Comment by waldyrious** [comment]
If we have Transifex for the website (due to Transifex Live, and given, if I understand correctly, that Crowdin doesn't have a similar feature) and Crowdin for the documentation, that seems like an acceptable compromise.

**Comment by Ismael-VC** [comment]
@waldyrious I don't know how I messed this:

* https://crowdin.com/page/website-localization-service

But I have already requested to start a new open source project using that, If I understand correctly this functionality is homologous to Transifex Live! :sparkles:

**Comment by waldyrious** [comment]
Yay :smile:

**Comment by StefanKarpinski** [comment]
Any reason not to merge this? @ViralBShah, @JeffBezanson, @tkelman?

**Comment by tkelman** [comment]
Seems okay to me, I had wondered the same thing every now and then.

**Comment by Ismael-VC** [comment]
This would be awesome! I feel that if this gets approved, It will be easier to have others contribute to the translations of the web page. 

I'll be spending this day trying to translate as much of the web site as I can in Spanish. As I've said in the past, Transifex has quality control mechanisms, so I wouldn't worry about unfinished, unpolished translations, basically because for a new language to show up in this widget ready for selection, we would ask (and I'm sure everyone would expect) for at least ~90% of completion for the translation or something like that.

The tricky part if figuring out how to attract more volunteers, but I can figure that out easier with this being an actual option, not a maybe thing.

**Comment by ViralBShah** [comment]
What's the status here? Should we close this for now given there hasn't been much movement?

**Comment by waldyrious** [comment]
@ViralBShah, the last words in the thread were of approval, so I'm afraid I can't follow your reasoning that this should be closed. For what it's worth, I am certainly willing to help out with the Portuguese translations, but I haven't dedicated much time to that so far, not the least because this not being merged poses a risk that such effort could go to waste. 

I'm sure @Ismael-VC is still interested and willing to do any additional adjustment to get this PR into a mergeable state that may be necessary.

**Comment by ViralBShah** [comment]
I was suggesting closing because I thought that interest had dropped and there was no follow up. I would certainly merge if the translations were in place. Or do we need a couple to get going on this and add more later?

I guess the right question here is - what are the next steps? Also is transifex the thing to go with or are there alternatives we should check for?

**Comment by waldyrious** [comment]
@Ismael-VC will probably be the best person to answer this :) I'll ping him on Gitter.

**Comment by Ismael-VC** [comment]
Hello everyone!

I'll try to state the current status and future actions that need to be done, the best I can.

1. At some point I had a large portion of the Julia site already translated in Spanish, there where concerns about the need for them at all and the quality:

    * https://github.com/JuliaLang/julialang.github.com/issues/187#issuecomment-121899134

    > The only concern I have is keeping all the versions in sync. It is really tough to keep eyes on all of the non-english communities and **if the page is not up-to-date the image of the project will suffer**, possibly without most of us even noticing. In short, given fewer eyeballs, slipping up becomes easier.

    > A small survey regarding other languages and if they have internationalisation on their homepage, do correct me if I missed it in a menu somewhere:

    > Python, no.
    > Ruby, yes.
    > Rust, no.
    > Go, no.

    I think that in order to not hurt the image of Julia, we would need the community support in advance, what I mean is that we should promote and encourage people to work the translations, and state that it's a beta feature, if other languages have support for internationalization or not  I think is irrelevant, because I don't care about those.

    At some point it seemed to me that this was going to be merged (it's been two years almost, and I still wait for approval), but then I had the impression that the translations were expected to be finished and of quality from the get go, and that is something I can't do alone for Spanish for example.

    We need collaboration and support from the higher ups, @waldyrious states correctly:

    > this not being merged poses a risk that such effort could go to waste.

    This is the only thing stopping me from translate a string at a time on my cellphone and on my free time, I and others do it with pleasure, but I didn't see that much interest from native English speakers at the time, and I was not willing to waste time if this wasn't considered.


2. There were several follow ups, I answered all the questions that arose, I tested several different platforms, and I don't want to test anymore, IMO Transifex is ideal for this, and unless somebody else is willing to prove the contrary, I'm going to keep rooting at Transifex for the web translation. The GUI has changed a bit, but it's just a mater of getting used to again.

3. The script to add the option to the web site is still the same, so this PR should still work unchanged.

4. In order to add a new language I would ask that at least the front page is fully translated for starters.

5. In short I think we have a chicken and the egg paradox here, my impression is that this would have been merged once translations were done, but translations wont be made by others, unless this is first merged, and ensures their work wont go to waste.

6. Transifex uses development and production tiers, so that all the current work that has already been done is still there and won't be visible until it's moved to production, in order to preach with the example, I will update the front page of the Spanish site to full translation and move it to production, if this get's merged, then I'll continue to do the rest, and stir the Juliasphere social media and what not in order to get help.

7. Just like there temporary banners for JuliaCon and GSOC for news, It would be nice if we could announce there that this beta feature is online and this way no one will expect 100 % translations and we will get people to contribute to their own native languages.

8. Lastly I will start to make a blog post about how to use Transifex to contribute to this project, that is my only concern, so If it's ok with you guys I can update the Spanish from page as I said and make this blog post ASAP, so we can reference it from the suggested banner in point *7*

As always if there is any doubt, please don't hesitate to ping me and I will gladly try to answer them. My interest for this has not died, but I'd love to see some compromise and support from the Julia devs, I have had support from volunteer translators, but **we need your blessing**. I'm always open for discussions that will lead us to improve the current PR and Julia-i18n as a whole.

* https://gitter.im/JuliaLangEs/julia-i18n

**Comment by Ismael-VC** [comment]
You can still se here:

* http://julialanges.github.io

How everything would look, there are some paragraphs that were updated since the last time I translated it, so you can see a mix in Spanish and English, that is how it looks when it's out of sync, its easily noticeable and fixed using Transifex.

If you guys really think this is hurting the Julia image, then I apologize because even in it's unfinished form I use this partially translated web site 24/7 as reference to any new Spanish speaker user I have come across.

**Comment by waldyrious** [comment]
I subscribe everything @Ismael-VC said, and will add that a simple disclaimer at the top of the translated pages, saying that this is a community effort, so there could be errors or out-of-date info, and most importantly, pointing people to how they can easily collaborate in improving the translations, would be sufficient for us to get the benefits (both outwards -- expanded reach thanks to i18n --, and inwards -- a larger pool of engaged contributors to the project, beyond coding) while avoiding the aforementioned downsides :)

**Comment by Ismael-VC** [comment]
@ViralBShah the Spanish version of the website is 90% translated as of now.

**Comment by Ismael-VC** [comment]
@ViralBShah sorry for double ping,

> I would certainly merge if the translations were in place.

The translation at least for Spanish has been in place for about a year or so, please LGTM.

Also notice that:

* http://julialanges.github.io

Is the **staging domain** I talked about earlier.

I have also made some noise in the juliasphere, I hope we can get more contributors once this is in place. Thanks in advance!

Spanish team:

image

Spanish translation:

image

image

**Comment by ViralBShah** [comment]
I feel like the only way to get more contributions is to get this merged. Let's wait another day or so to see if others chime in.

**Comment by Ismael-VC** [comment]
bump

In just this two days there has been requests for Russian, Basque, Turkish, Danish and Finish, plus the ones that are already there, @tomaklutfu is going strong in the Turkish translation achieving almost 10 % 🎉 in just a couple of days, the team has also gotten bigger.

I think it's obvious people want this feature and are even willing to provide the translations, 1+ year is enough to see if others chime in IMHO, and finally there is consensus of approval. 

image

**Comment by Ismael-VC** [comment]
@ViralBShah also Spanish is ready, it just need more eyes to review, all the site is translated in Spanish except for individual publications, but I'm already translating *why we created Julia* and I want 100% translation, after that localizatiosn for variants of Spanish can be developed based in the generic Spanish one. 

I'd like to thank @waldyrious and @codeneomatrix for their support and helping me share project and team coordinator roles among other things, and of course to everyone else involved too!

Thanks for sharing your spare time doing this, you guys are awesome!

**Comment by Ismael-VC** [comment]
image

**Comment by ViralBShah** [comment]
Great going! I am glad I revived this thread by suggesting to close it. :-)

**Comment by ViralBShah** [comment]
I am ViralBShah on transifex now. Can you please add me to project maintainers?

**Comment by ViralBShah** [comment]
Seems like Turkish ought to be available in the drop down menu too. There were also some folks who had done a simplified Chinese translation of the Julia manual - and perhaps we may get some contributions for the website too.

**Comment by ViralBShah** [comment]
Is it possible in the language dropdown to also have something that will invite people to contribute translations?

**Comment by Ismael-VC** [comment]
> Great going! I am glad I revived this thread by suggesting to close it. :-)

Thank's everyone for your support!

> I am ViralBShah on transifex now. Can you please add me to project maintainers?

@ViralBShah I've added you a project administrator, I've also made you the Chinese language coordinator, collaborator at [julialanges.github.com](https://github.com/JuliaLangEs/julialanges.github.com) and send you an invite to be an owner of JuliaLangEs, so you'll have full access to the whole project.

> Seems like Turkish ought to be available in the drop down menu too.

Turkish is going strong indeed! Previously I suggested the following:

> In order to add a new language I would ask that at least the front page is fully translated for starters.

You can see all language current progress in staging:

* http://julialanges.github.io

I am making a blog post about tips and tricks, like completing the front page first and how to do it, but as it was only a suggestion, I will put it online now, as we can change that or push more languages at any time to production.

> Is it possible in the language dropdown to also have something that will invite people to contribute translations?

I'n mot sure about that, let me check out.






> In order to add a new language I would ask that at least the front page is fully translated for starters.

**Comment by waldyrious** [comment]
@Ismael-VC sorry about asking this here (shall we start a julia-i18n google group, @ViralBShah?), but is there a way to setup a sub-goals within the website (e.g. per-page), so that translators have more reachable goals and can track progress towards them, and particularly can visualize progress towards having their language enabled live?

**Comment by Ismael-VC** [comment]
@waldyrious indeed that is a good idea, I think it's time for a proper stand alone Julia-i18n organization, currently it's under JuliaLangEs, I'll add one team per language, now that the ball is rolling, I started with one team for all, just for simplicity at the beginning.

I wont have time today until the afternoon, please let me know if someone beats me to it. 😄 

> but is there a way to setup a sub-goals within the website (e.g. per-page)

One can use Transifex live to translate the page itself like "real time" so to speak, the online editor has more features, but string are not sorted in this view.

Compare live view:
transifex1

Editor view:
transifex2

I'll explain my current workflow in the blog post, If I need to translate a specific string it can be searched in the editor view, while the live view gives context. Typically I have both view open at all times when translating.

**Comment by waldyrious** [comment]
I will certainly be using the Live editor, it's much more exciting that way :D

Looking forward to the blog post. Let me know if you'd like another set of eyes to take a look pre-publication.

**Comment by waldyrious** [comment]
Also, I strongly support a Julia-i18n organization. It would be nice to have an issue tracker for tracking these sorts of improvements (adding an invitation to collaborate, adding sub-goals, which translatable assets to add next, which platforms to use cf. https://github.com/JuliaLang/julialang.github.com/pull/250#issuecomment-121787574, etc.) and possible issues/questions people may run into.

**Comment by Ismael-VC** [comment]
@waldyrious done! :) I have added you and a few others as collaborators, I'll start creating resources like mailing list and migrate the i18n Gitter chat there, we also need a logo!

* https://github.com/Julia-i18n

For now let us continue planning ahead at the current Gitter chat room for i18n:

* https://gitter.im/JuliaLangEs/julia-i18n

**Pull request merged**
