### PR TITLE
Update julia.bib to add OPV16

### PR DESCRIPTION
**Pull request by gersonjferreira**

### CODE REVIEW

**Comment by jiahao** [comment]
Thanks. Please include an appropriate entry to your paper in `_EDIT_ME_index.md `. If you have `pandoc` and `pandoc-citeproc` installed you can also generate `index.md` also (or I can do it for you if you have trouble).

**Comment by jiahao** [comment]
Oh, that is #370

**Comment by gersonjferreira** [comment]
I didn't have these packages installed. I'll try them next time. We only
need them to generate index.md, right? Now I understand better. Sorry for
the trouble and thanks for generating index.md for me.

So it is not possible to make a pull request to this particular page fully
on the browser, right? I should clone the repo and run the commands to
generate index.md.

Do you know if the command line "git pull-request" works fine?

**Comment by jiahao** [comment]
> So it is not possible to make a pull request to this particular page fully on the browser, right? I should clone the repo and run the commands to generate index.md.

Not for the publication list at the moment, since it is generated from the BibTeX entries.

> Do you know if the command line "git pull-request" works fine?

Yes, if you are using [`hub`](https://github.com/github/hub) and aliasing `git=hub`.

**Pull request merged**
