### PR TITLE
Update PyPlot example

### PR DESCRIPTION
**Pull request by bcavileer**
sin() and cos() changed to sin.() and cos.()
linestyle is now a symbol

### CODE REVIEW

**Comment by ViralBShah** [comment]
The PyPlot.jl README itself still does not use the symbol for linestyle. Is this in a released version of PyPlot.jl?

**Comment by johnfgibson** [comment]
PyPlot 2.3.2 in julia-0.6.0 accepts any of ``"--"``, ``"dashed"``, ``:dashed`` as a value for ``linestyle`` with no deprecation warnings on any of them. I just checked.

Agreed that sin() and cos() should change to sin.() and cos.(); the former do give deprecation warnings.

**Comment by ChrisRackauckas** [comment]
Yes, dots should stay. But I would respect the way the author of PyPlot writes the tutorial, or at least put a comment after that the other is allowed.

**Comment by ViralBShah** [comment]
@stevengj Do you have a preference on the way we do `linestyle` here?

**Comment by stevengj** [comment]
This depends on Matplotlib, not PyPlot: PyPlot just passes this keyword through to Matplotlib without looking at it it.

The [matplotlib documentation](https://matplotlib.org/gallery/lines_bars_and_markers/line_styles_reference.html?highlight=line%20style%20reference) seems to prefer `"--"`, but [`"dashed"` also works](https://matplotlib.org/api/_as_gen/matplotlib.lines.Line2D.html#matplotlib.lines.Line2D).

PyCall converts Julia Symbols into Python strings, so `:dashed` or `Symbol("--")` should also work.  But since the Matplotlib documentation uses strings, I would suggest using a string as well.

**Comment by ViralBShah** [comment]
Ok - clearly makes sense to leave it as a string. Can merge once fixed.

**Pull request merged**
