### PR TITLE
Juno download links

### PR DESCRIPTION
**Pull request by one-more-minute**
@ViralBShah suggested adding some Juno download links to the Julia downloads page, so I've tried to do that in a sane way. Suggestions are very welcome.

Incidentally, this page could probably be earmarked for a rewrite, a lot of it is crufty or even out of date.

### CODE REVIEW

**Comment by ViralBShah** [comment]
Should we put some text and a link to Julia-LT there about where to file Juno related issues?

**Comment by ViralBShah** [comment]
Are these codesigned? It didn't alert me on the mac, but that may be perhaps because I had given permissions to the OS to allow Juno, when I first tried it out.

**Comment by ViralBShah** [comment]
The downloads page rewrite has been on my mind for a while. To start with, we can just move much of the OS level details and graphics to a different page, and make this simply about getting to Julia: REPL-based, Juno, or JuliaBox. I think it will be nice to add some screenshots too.

**Comment by one-more-minute** [comment]
+:100: to some Julia/JuliaBox/Juno screenshots, that could really help draw people in. Might be nice to have those on the home page along with a nice big "download" link.

The docs explain where to get help and post issues, but it is a little indirect; I'll add more info on help.

And yes, builds are now all codesigned thanks to @staticfloat :)

**Pull request merged**
