### PR TITLE
Highlight code in `iteration` blog post.

### PR DESCRIPTION
**Pull request by Carreau**
I enjoyed @timholy post , 

I prefer it highlighted.  (only drawback is the style of some unicode that are red-ish
screen shot 2016-02-06 at 15 00 23

You should be able to [view the diff without whitespace changes](https://github.com/JuliaLang/julialang.github.com/pull/327/files?w=1) by appending `?w=1`

### CODE REVIEW

**Comment by tkelman** [comment]
Makes sense to me?

**Comment by StefanKarpinski** [comment]
Thanks, @Carreau!

**Comment by timholy** [comment]
Just noticed this. Thanks for fixing it!

**Comment by timholy** [comment]
I'm still not seeing highlighting when I visit the page, though. Any ideas?

**Comment by Carreau** [comment]
> I'm still not seeing highlighting when I visit the page, though. Any ideas?

Hum, no, if I just run jekyll locally I get the highlighting.

Might be related to recent github update:

https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0

**Pull request merged**
